project:
  type: website
  output-dir: docs

website:
  title: "UW Quarto Site Template"
  favicon: images/favicon.ico
  navbar:
    logo: images/header-logo.png
    right:
      - icon: github
        href: https://github.com/UW-Madison-DSI/uw_quarto_site_template
        aria-label: GitHub
  sidebar:
    style: "floating"
  page-footer:
    background: dark
    left: UW-Madison Quarto Template [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/UW-Madison-DSI/uw_quarto_site_template){target=_blank}
    right: This template is built with [Quarto](https://quarto.org/){target=_blank} by the [UW Data Science Institute](https://datascience.wisc.edu/institute/)
    
execute:
  echo: false
  message: false
  warning: false

metadata-files:
  - sidebar.yml

format:
  html:
    theme: [default, custom.scss]
    toc: true
    mainfont: Red Hat Text



